---
title: custom_extrude
---

<Tabs items={["Functions"]}>

<Tab value={"Functions"}>

<PyFunction name={"custom_extrude"} type={"(to_extrude=None, plane=Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, 1)), amount=None, dir=None, until=None, target=None, both=False, taper=0.0, clean=True, mode=Mode.ADD) -> Part"}>

Part Operation: extrude

Extrude a sketch or face by an amount or until another object.

Args:
    to_extrude (Union[Face, Sketch], optional): object to extrude. Defaults to None.
    amount (float, optional): distance to extrude, sign controls direction. Defaults to None.
    dir (VectorLike, optional): direction. Defaults to None.
    until (Until, optional): extrude limit. Defaults to None.
    target (Shape, optional): extrude until target. Defaults to None.
    both (bool, optional): extrude in both directions. Defaults to False.
    taper (float, optional): taper angle. Defaults to 0.0.
    clean (bool, optional): Remove extraneous internal structure. Defaults to True.
    mode (Mode, optional): combination mode. Defaults to Mode.ADD.

Raises:
    ValueError: No object to extrude
    ValueError: No target object

Returns:
    Part: extruded object
    :param to_extrude:
    :param plane:

<PySourceCode >

```python
def custom_extrude(
    to_extrude: Union[Face, Sketch] = None,
    plane: Plane = Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, 1)),
    amount: float = None,
    dir: VectorLike = None,  # pylint: disable=redefined-builtin
    until: Until = None,
    target: Union[Compound, Solid] = None,
    both: bool = False,
    taper: float = 0.0,
    clean: bool = True,
    mode: Mode = Mode.ADD,
) -> Part:
    """Part Operation: extrude

    Extrude a sketch or face by an amount or until another object.

    Args:
        to_extrude (Union[Face, Sketch], optional): object to extrude. Defaults to None.
        amount (float, optional): distance to extrude, sign controls direction. Defaults to None.
        dir (VectorLike, optional): direction. Defaults to None.
        until (Until, optional): extrude limit. Defaults to None.
        target (Shape, optional): extrude until target. Defaults to None.
        both (bool, optional): extrude in both directions. Defaults to False.
        taper (float, optional): taper angle. Defaults to 0.0.
        clean (bool, optional): Remove extraneous internal structure. Defaults to True.
        mode (Mode, optional): combination mode. Defaults to Mode.ADD.

    Raises:
        ValueError: No object to extrude
        ValueError: No target object

    Returns:
        Part: extruded object
        :param to_extrude:
        :param plane:
    """
    # pylint: disable=too-many-locals, too-many-branches
    to_extrude_faces: list[Face]

    to_extrude_faces = (
        [*to_extrude]
        if isinstance(to_extrude, (tuple, list, filter))
        else to_extrude.faces()
    )

    new_solids: list[Solid] = []

    for face in to_extrude_faces:
        for direction in [1, -1] if both else [1]:
            if amount:
                if taper == 0:
                    new_solids.append(
                        Solid.extrude(
                            face,
                            direction=plane.z_dir * amount * direction,
                        )
                    )
                else:
                    new_solids.append(
                        Solid.extrude_taper(
                            face,
                            direction=plane.z_dir * amount * direction,
                            taper=taper,
                        )
                    )

            else:
                new_solids.append(
                    Solid.extrude_until(
                        section=face,
                        target_object=target,
                        direction=plane.z_dir * direction,
                        until=until,
                    )
                )

    return Part(ShapeList(new_solids).solids())
```

</PySourceCode>

<div >

<PyParameter name={"to_extrude"} type={"Union[Face, Sketch]"} value={"None"} />
<PyParameter name={"plane"} type={"Plane"} value={"Plane(origin=(0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, 1))"} />
<PyParameter name={"amount"} type={"float"} value={"None"} />
<PyParameter name={"dir"} type={"VectorLike"} value={"None"} />
<PyParameter name={"until"} type={"Until"} value={"None"} />
<PyParameter name={"target"} type={"Union[Compound, Solid]"} value={"None"} />
<PyParameter name={"both"} type={"bool"} value={"False"} />
<PyParameter name={"taper"} type={"float"} value={"0.0"} />
<PyParameter name={"clean"} type={"bool"} value={"True"} />
<PyParameter name={"mode"} type={"Mode"} value={"Mode.ADD"} />

</div>

<PyFunctionReturn type={"build123d.topology.Part"} />

</PyFunction>

</Tab>

</Tabs>