---
title: Wire
---

A wire is a sequence of connected primitives that form a closed loop.

## Attributes

<PyAttribute name={"edges"} type={"List[Union[Line, Circle, Arc]]"} value={null} />

<PyAttribute name={"constraints"} type={"Optional[list]"} value={"None"} />

## Functions

<PyFunction name={"to_json"} type={"(self) -> Dict[str, Any]"}>

<PySourceCode >

```python
def to_json(self) -> Dict[str, Any]:
    return {
        "edges": [e.to_json() for e in self.edges],
    }
```

</PySourceCode>

<div >

<PyParameter name={"self"} type={null} value={null} />

</div>

<PyFunctionReturn type={"typing.Dict[str, typing.Any]"} />

</PyFunction>

<PyFunction name={"to_python"} type={"(self, index=0) -> str"}>

<PySourceCode >

```python
def to_python(self, index: Optional[int] = 0) -> str:
    return f"Wire([{', '.join(e.name for e in self.edges)}])"
```

</PySourceCode>

<div >

<PyParameter name={"self"} type={null} value={null} />
<PyParameter name={"index"} type={"Optional[int]"} value={"0"} />

</div>

<PyFunctionReturn type={"str"} />

</PyFunction>

<PyFunction name={"bounding_box_area"} type={"(self) -> float"}>

<PySourceCode >

```python
def bounding_box_area(self) -> float:
    all_points = np.concatenate([edge.bbox for edge in self.edges], axis=0)
    bbox = np.stack(
        [np.min(all_points, axis=0), np.max(all_points, axis=0)], axis=0
    )

    bbox_min, bbox_max = bbox[0], bbox[1]

    return np.prod(bbox_max - bbox_min)
```

</PySourceCode>

<div >

<PyParameter name={"self"} type={null} value={null} />

</div>

<PyFunctionReturn type={"float"} />

</PyFunction>

<PyFunction name={"plot"} type={"(self) -> None"}>

<PySourceCode >

```python
def plot(self) -> None:
    visualize_lines(self.edges, inner_edges=[], ax=None)
    plt.show()
```

</PySourceCode>

<div >

<PyParameter name={"self"} type={null} value={null} />

</div>

<PyFunctionReturn type={"None"} />

</PyFunction>

<PyFunction name={"to_occ"} type={"(self) -> Any"}>

<PySourceCode >

```python
def to_occ(self) -> Any:
    from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeWire

    wire_builder = BRepBuilderAPI_MakeWire()
    for edge in self.edges:
        occ_edge = edge.to_occ()
        wire_builder.Add(occ_edge)
    return wire_builder.Wire()
```

</PySourceCode>

<div >

<PyParameter name={"self"} type={null} value={null} />

</div>

<PyFunctionReturn type={"typing.Any"} />

</PyFunction>

<PyFunction name={"__init__"} type={"(self, edges, constraints=None) -> None"}>

<div >

<PyParameter name={"self"} type={null} value={null} />
<PyParameter name={"edges"} type={"List[Union[Line, Circle, Arc]]"} value={null} />
<PyParameter name={"constraints"} type={"Optional[list]"} value={"None"} />

</div>

<PyFunctionReturn type={"None"} />

</PyFunction>